services:
  traefik:
    image: traefik:v3.6.6
    container_name: traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--log.level=${TRAEFIK_LOG_LEVEL:-DEBUG}"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.lehttp.acme.httpchallenge=true"
      - "--certificatesresolvers.lehttp.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.lehttp.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.lehttp.acme.httpchallenge.entrypoint=web"
      - "--api.dashboard=false"
    env_file:
      - ../.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/letsencrypt/acme.json"
      - "./traefik.yml:/traefik.yml:ro"
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
